name: "unit tests for GO project"
description: "Runs unit tests for GO project"
inputs:
  workdir:
    description: 'Working directory of the service under test'
    required: true
  goversion:
    description: 'Go version to run tests with'
    required: true
runs:
  using: docker
  image: 'docker://golang:${{ inputs.goversion }}'
  args:
    - sh
    - -c
    - 'cd ${{ inputs.workdir }} && make test-unit'