name: service-echo-pr
on:
  pull_request:
    paths:
      - 'svc/echo/**'
      - 'toolkit/**'
      - 'Makefile'
      - '.github/workflows/svc.echo-pr.yml'
env:
  workdir: 'svc/echo'
  go-version: '1.16'
defaults:
  run:
    shell: bash
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          working-directory: '${{ env.workdir }}'
          args: '--config "${GITHUB_WORKSPACE}/ci/golangci.yml"'
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '${{ env.goversion }}'
      - run: make test-unit
        working-directory: '${{ env.workdir }}'
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '${{ env.goversion }}'
      - run: make test-integration
        working-directory: '${{ env.workdir }}'
  build:
    runs-on: ubuntu-latest
    needs: [ 'linter', 'unit-tests', 'integration-tests' ]
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: '${{ env.workdir }}/Dockerfile'
          push: false # should push in real example
          tags: 'svc/echo:PR-${{ github.event.pull_request.number }}'