name: toolkit-pull-request
on:
  push:
    paths:
      - 'toolkit/**'
      - 'Makefile.go.mk'
      - '.github/workflows/toolkit*'
      - '.github/actions/go-*'
env:
  workdir: 'toolkit'
  go-version: '1.16'
defaults:
  run:
    shell: bash
jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          working-directory: '${{ env.workdir }}'
          args: '--config "${GITHUB_WORKSPACE}/ci/golangci.yml"'
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '${{ env.goversion }}'
      - run: make test-unit
        working-directory: '${{ env.workdir }}'
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '${{ env.goversion }}'
      - run: make test-unit
        working-directory: '${{ env.workdir }}'