name: toolkit-pull-request
on:
  push:
    paths:
      - 'toolkit/**'
      - 'Makefile.go.mk'
      - '.github/workflows/toolkit*'
      - '.github/action/go-*'
env:
  workdir: 'toolbox'
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/go-test-unit
        with:
          workdir: '${{ env.workdir }}'
      - uses: golangci/golangci-lint-action@v2
        with:
          working-directory: '${{ env.workdir }}'
          args: '--config "${GITHUB_WORKSPACE}/ci/golangci.yml"'
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/go-test-integration
        with:
          workdir: '${{ env.workdir }}'