name: toolkit-pull-request
on:
  push:
    paths:
      - 'toolkit/**'
      - 'Makefile.go.mk'
      - '.github/workflows/toolkit*'
      - '.github/action/go-*'
defaults:
  run:
    working-directory: toolbox
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/go-test-unit
        with:
          workdir: 'toolkit'
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/go-test-integration
        with:
          workdir: 'toolkit'